settings:
  debug: false
  # Hex color codes are supported in all messages! Use <#hex> to insert them.
  splitsouls:
    cannot-split:
      - '&c&l(!)&r &cYou don''t have enough souls to do that!'
    not-a-soulgem:
      - '&c&l(!)&r &cThis item is not a soul gem!'
    usage:
      - '&7Usage: &f/splitsouls [amount]&r'
    split:
      - '&a&l(!)&r &aSoul gem has been split.'
  soul-use:
    enabled: true
    messages: # Use %amount% to insert the amount of souls used.
      - '&e&l** SOULS: &6&n&l%amount%&r&e&l **'
  soul-mode:
    enabled: true
    messages:
      enabled:
        - ' '
        - '&a&l** SOUL MODE: &nON&r&a&l **'
        - '&7Your soul enchantments will now drain souls.'
        - ' '
      disabled:
        - ' '
        - '&c&l** SOUL MODE: &nOFF&r&c&l **'
        - '&7Your soul enchantments will no longer drain souls.'
        - ' '
      empty:
        - ' '
        - '&c&l** SOUL MODE: &nOFF&r&c&l **'
        - '&7You have no soul gems left!'
        - ' '

particles:
  # Particles: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  y-offset: 1.0
  soul-enable:
    type: 'REDSTONE'
    colorR: 91
    colorG: 245
    colorB: 83
    amount: 20
    spread: 1.25
  soul-disable:
    type: 'REDSTONE'
    colorR: 250
    colorG: 55
    colorB: 74
    amount: 20
    spread: 1.25
  soul-idle:
    type: 'ENCHANTMENT_TABLE'
    amount: 8
    spread: 0.75
  soul-use:
    type: 'SPELL_WITCH'
    amount: 15
    spread: 0.75

sounds:
  # Sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # Format: SOUND:VOLUME:PITCH
  toggle-soul-mode-on:
    - 'BLOCK_RESPAWN_ANCHOR_CHARGE:1.0:0.1'
    - 'ITEM_CHORUS_FRUIT_TELEPORT:1.0:1.7'
  toggle-soul-mode-off:
    - 'BLOCK_GLASS_BREAK:1.0:0.1'
  soul-use:
    - 'ENTITY_GENERIC_EAT:10.0:1.0'
  combine-soul-gems:
    - 'ENTITY_EXPERIENCE_ORB_PICKUP:1.0:1.0'
  split-soul-gems:
    - 'BLOCK_GLASS_BREAK:1.0:1.4'