name: SoulGems
version: '${project.version}'
main: me.vexmc.enchantments.SoulGemsPlugin
depend: [AdvancedEnchantments]
api-version: 1.20
authors: [owengregson]
commands:
  splitsouls:
    description: "Splits off a soul gem with the specified amount of souls."
    usage: "/splitsouls [amount]"
  reload:
    description: "Reloads the configuration."
    usage: "/soulgems reload"
    permission: soulgems.command.reload
  authors:
    description: "Displays the creators of the plugin."
    usage: "/soulgems authors"
    permission: soulgems.command.authors